# Generated by Django 2.1 on 2021-04-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('annotation', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateField()),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'курси',
                'ordering': ('start', 'name'),
            },
        ),
    ]
