# Generated by Django 2.1 on 2021-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lectures_number',
            field=models.IntegerField(default=1),
        ),
    ]
